### PR TITLE
Add support for a new ids

### PR DESCRIPTION
**Pull request by smly**
This PR adds new account title, level and avatar frames that appear in recent games.

Here is the list of games where each ID appears:

* `220421-003cd367-72a0-4a81-ad17-ff11f41fc05b` ... `600035: 千磨百錬`
* `220421-0e5c4c5c-3b63-475b-928d-d5730c5d796f` ... `305529: 秋霜の剣`
* `220421-08dcdc54-9596-4f0a-808c-4bd42dc62339` ... `10705`
* `220421-36598629-1eaa-4907-9d65-a00518ecbd16` ... `10706`
* `220421-486333a6-8d26-49dc-9eb0-0409b29787b4` ... `305533: (詳細不明)`
* `220421-5ca6a175-d750-4098-8692-64c8057fa73e` ... `305534: (詳細不明)`
* `220421-c6df5914-f381-4796-92e5-4154705acd4b` ... `305531: (詳細不明)`
* `220421-a134e578-8f3b-4404-ab06-f526aea447da` ... `20705`

### CODE REVIEW

**Comment by Cryolite** [comment]
Thank you for the PR. This repository, as for the operation policy, first merge a PR into the `develop` branch, wait at least a day, and then merge it into the `master` branch. Therefore, the merge target of this PR is changed to the `develop` branch.

**Comment by Cryolite** [comment]
LGTM.

**Review by Cryolite — COMMENTED** [review]
LGTM.

**Comment by Cryolite** [comment]
Sorry. I mistakenly closed this PR without merging.

**Comment by Cryolite** [comment]
The commits in this PR will be merged into the `master` branch within one to a few days.

**Comment by smly** [comment]
Thank you!

**Comment by Cryolite** [comment]
These commits has been merged into `master` branch.

**Pull request merged**
